<?php
/**
 * Plugin Name: Supplang
 * Description: Flexible language manager that allows for a complete separation between UI language and content language.
 * Version:     1.1.0
 * Author:      Mathias Oberson - MEI
 * Author URI:  https://heig-vd.ch/rad/instituts/mei/
 * Text Domain: supplang
 * Domain Path: /languages
 */

// THIS FILE IS AUTOMATICALLY GENERATED !
// DO NOT ALTER ITS CONTENT

// Bootstrap the plugin.
require_once 'bootstrap.php';
